### PR TITLE
env variable bugfix

### PR DESCRIPTION
**Pull request by ben-bay**
Resolves issue #201

### CODE REVIEW

**Comment by lucpeterson** [comment]
build is failing on unit test for $PATH
>       assert not TestMerlinStudy.file_contains_string(
536            self.study.expanded_spec.path, "$PATH"
537        )

**Comment by ben-bay** [comment]
> build is failing on unit test for $PATH
> 
> > ```
> >   assert not TestMerlinStudy.file_contains_string(
> > ```
> 
> 536 self.study.expanded_spec.path, "$PATH"
> 537 )

Good catch. I'll reverse the test, so that env variable _should_ be found in the step's `run.cmd`.

**Comment by ben-bay** [comment]
@lucpeterson @koning in the past, environment variable expansion was section-agnostic; it occurred equally on every line of the spec. I'll now be fixing this to only happen in non-shell cmd sections. Since this requires a bit of refactoring, I marked this PR as a WIP, probably to be finished by tomorrow.

**Comment by lucpeterson** [comment]
So I think a lot of these changes need doc strings, comments, etc.
We also should add user documentation somewhere about when/how environment variables are applied. This is a big change and we want to be clear to users (and future us!) about what's going on.

**Comment by koning** [comment]
Have you tested this on LC with any of the flux test specs?

**Comment by ben-bay** [comment]
> Have you tested this on LC with any of the flux test specs?

@koning Ran `flux_par` successfully, the steps `data` and `stop_workers` didn't have a `MERLIN_FINISHED` file but there was no discernible error anywhere.

**Comment by ben-bay** [comment]
> Have you tested this on LC with any of the flux test specs?

Yes, all variable expansion works as expected, however some of the flux examples are breaking, probably because the flux team has changed the interface again.

**Comment by lucpeterson** [comment]
Does this work with $SYS_TYPE in the flux path definition?

**Comment by lucpeterson** [comment]
specifically on different machines

**Comment by ben-bay** [comment]
@lucpeterson Joe actually asked this same question. Yep $SYS_TYPE works. (aslo it's ignored in shell commands)

**Pull request merged**
