### PR TITLE
Release 1.9.0

### PR DESCRIPTION
**Pull request by ryannova**
Updated changes before release 1.9.0.

### CODE REVIEW

**Comment by ryannova** [comment]
I'm not sure if we are dropping support for 3.6. It seems more like that python 3.6 tests can't be run on github lately. I noticed this issue started on Tuesday. I'm not sure what is going on.

**Comment by lucpeterson** [comment]
Bryan G has a PR in that drops 3.6 and adds 3.11. 3.6 is past end of life and GitHub runners don’t fully support them now. Let’s make the needdd changes on Bryan’s PR

——
J. Luc Peterson, PhD (he/him)
LLNL
***@***.***

On Dec 15, 2022, at 11:55 AM, Ryan Lee ***@***.***> wrote:

﻿

I'm not sure if we are dropping support for 3.6. It seems more like that python 3.6 tests can't be run on github lately. I noticed this issue started on Tuesday. I'm not sure what is going on.

**Comment by ryannova** [comment]
It seems like Bryan's PR has already been approved. Do you want me to merge his changes in and update the release?

**Comment by bgunnar5** [comment]
I haven't updated pypi, is this something I need to change in the codebase? The only changes I made so far regarding the 3.6 drop and 3.11 support were modifying the push-pr_workflow.yml file to remove 3.6 tests and add 3.11.

P.S. it's Brian with an i but I'll let it slide this time

**Comment by lucpeterson** [comment]
@ryannova can you de-conflict this with the PRs that just went in (@bgunnar5 and the GitHub bot that fixed a security concern)? Then I bet the tests will be passing and we can go ahead with it

**Comment by koning** [comment]
@bgunnar5 I think @lucpeterson needs to login to pypi and add you. It is just editing the information directly.

**Review by lucpeterson — APPROVED** [review]

**Pull request merged**
