### PR TITLE
Allows loading of nparrays of dtype=object

### PR DESCRIPTION
**Pull request by nkeilbart**
Couldn't load numpy arrays if dtype was set to object. The allow_pickle=True option appears to allow this to happen. Mainly suggesting this change as I couldn't load mixed numpy arrays for my after the sample generation.

### CODE REVIEW

**Comment by lucpeterson** [comment]
Update the CHANGELOG and this is good

**Comment by lucpeterson** [comment]
@nkeilbart pull in develop changes so we can see if tests are passing

**Comment by nkeilbart** [comment]
Alright I just merged in the recent updates.

**Comment by ryannova** [comment]
Addressed in #398

**Pull request closed without merging**
