### PR TITLE
Feature/luc/zfill dirs

### PR DESCRIPTION
**Pull request by lucpeterson**
This addresses #173 

Also fixed the bug whereby top level of directory hierarchy was always "0"

@ben-bay We will need to change the diagrams of directory structures for the hello world tutorial example, since the superfluous top layer will be gone. Also, Peter has removed the sample_index.txt file, which we don't need, so that'll need to be modded too

### CODE REVIEW

**Comment by ben-bay** [comment]
Great, is Peter's removal of sample_index.txt already in?

**Comment by lucpeterson** [comment]
@robinson96

**Comment by lucpeterson** [comment]
i'd like to wait until Peter takes a look at this
please don't merge yet

**Comment by ben-bay** [comment]
This works for me when I run it.

**Comment by robinson96** [comment]
I don't see any concerns here.

**Comment by lucpeterson** [comment]
@ben-bay  I think we're just waiting for the build to pass and then we're good to merge

**Pull request merged**
