### PR TITLE
Add Pytest Fixtures to Test Suite

### PR DESCRIPTION
**Pull request by bgunnar5**
The branch I'm requesting to merge in is where I've been working on upgrades to the test suite. This PR contains the pytest fixtures that will be really helpful for writing tests. I want this merged now so I can write tests for the `merlin monitor` command in #452  (and also the third PR of the status command will likely need this).

I plan on finding a way to use these fixtures to improve the integration test suite in the future too, but for now this is sufficient to assist with the other PRs.

### CODE REVIEW

**Comment by doutriaux1** [comment]
Thanks @bgunnar5 that looks nice (although seems to fail :) ). Are you planning to add coverage?

**Comment by bgunnar5** [comment]
@doutriaux1 I forgot to check pylint before drafting this PR (oops!) so that's why this is failing. I do have plans to add coverage but I'd like to get what I have now merged first so I can get #452 finished up.

**Comment by koning** [comment]
Seems to work for the most part on LC:

=========================== short test summary info ============================
ERROR unit/study/test_celeryadapter.py::TestActiveQueues::test_query_celery_queues
ERROR unit/study/test_celeryadapter.py::TestActiveQueues::test_get_running_queues
ERROR unit/study/test_celeryadapter.py::TestActiveQueues::test_get_queues_active
ERROR unit/study/test_celeryadapter.py::TestInactiveQueues::test_get_queues
======================== 63 passed, 4 errors in 52.25s =========================

**Comment by bgunnar5** [comment]
@koning the fixtures use the `merlin server` command to start up a local server. What you're seeing is likely the weird issue with the `merlin server` command where you have to run `export LC_ALL="C"` before attempting to start the server.

**Comment by koning** [comment]
Yep, that fixed it, looks good:

============================ 67 passed in 58.52s ==============================

**Review by koning — APPROVED** [review]

**Pull request merged**
