### PR TITLE
bugfix/server-pip-redis-conf

### PR DESCRIPTION
**Pull request by bgunnar5**
I added the *.conf to the recursive-include of the merlin server folder so that pip will add the redis.conf file to the wheel. I've also added a note on explaining how to fix an issue with `merlin server start` to get it to stop hanging.

### CODE REVIEW

**Review by koning — APPROVED** [review]

**Comment by lucpeterson** [comment]
Looks good to me too

From: Joe Koning ***@***.***>
Date: Friday, August 18, 2023 at 12:32 PM
To: LLNL/merlin ***@***.***>
Cc: Peterson, Luc ***@***.***>, Review requested ***@***.***>
Subject: Re: [LLNL/merlin] bugfix/server-pip-redis-conf (PR #443)

@koning approved this pull request.

**Comment by koning** [comment]
Does this work as well: ```export LC_ALL="C"```

**Comment by bgunnar5** [comment]
@koning I just tried it and yes it does. I'll add that to the docs too.

**Comment by koning** [comment]
OK, good. The C just means ignore user encodings.

**Review by ryannova — APPROVED** [review]
Looks good to me

**Pull request merged**
