### PR TITLE
Feature/openfoam wf update

### PR DESCRIPTION
**Pull request by koning**
Update learn.py to create missing plot
Add singularity base wf.

### CODE REVIEW

**Review by lucpeterson — COMMENTED** [review]
Are there tests we can add for this?

**Comment by koning** [comment]
Do the existing openfoam workflows have a test? Other than running the workflow what would be a good test?

**Comment by lucpeterson** [comment]
@ryannova and @bgunnar5 do you think we could add a test for this new workflow? It uses singularity to run a "real application" in a container and would be great to have that in the test suite. It'd also be nice to have the tutorial use this one (instead of having to build openFoam themselves)

**Comment by koning** [comment]
Two users have been unable to run the tutorial example (openfoam_no_docker) because of the openfoam access issue.

**Comment by lucpeterson** [comment]
Do the changes to the makefile necessitate a change to the isort version? Do we need to change any requirements?

**Review by lucpeterson — APPROVED** [review]

**Pull request merged**
