### PR TITLE
Bugfix/ben/expand name

### LINKED ISSUE #215: [FEAT] Allow programmatic assignment of description.name
## 🚀 Feature Request

**Describe the solution you'd like**
The ability to use this: `merlin run spec.yaml --vars STATE=Illinois ID=42`
And alter this:
```
description:
    name: $(STATE)_State$(ID)
    description: ...
```

### PR DESCRIPTION
**Pull request by ben-bay**
Fixes #215 

Note: must include user variable in `env` for name expansion to work from command line.

### CODE REVIEW

**Comment by lucpeterson** [comment]
I'd like to put some tests in that test this functionality. It seems like it could potentially break stuff. Particularly things like restart, query, etc.

**Comment by lucpeterson** [comment]
is this failing tests?

**Comment by ben-bay** [comment]
> is this failing tests?

Looks as if. I had these passing manually, so shouldn't be too tough to fix.

**Comment by ptbremer** [comment]
I just tried this out and it does not yet fully work. The $(NAME) does get correctly expanded at the end but still after any sample generation script is run. 

Following the examples, I am creating the samples in the Merlin block 

```
merlin:
    samples:
        generate:
            cmd: |
                cp -r $(SPECROOT)/scripts $(MERLIN_INFO)/
                python $(SCRIPTS)/make_unit_samples.py <snip>
                python $(SCRIPTS)/make_scaled_samples.py <snip>               
                 
        file: $(MERLIN_INFO)/samples.npy
        column_labels: $(PARAMETERS)
```

But at the point this is executed $(SPECROOT) is still not correctly expanded. In fact it seems to be empty. 

/EpiCast-WF/output/_20200523-075936/merlin_info: No such file or directory

This is kind of strange since the directory is correctly created and named at the end

**Comment by ben-bay** [comment]
@ptbremer good catch, looking at the cause of this now.

**Comment by lucpeterson** [comment]
do we have a test for this?

**Comment by ben-bay** [comment]
> do we have a test for this?

I've built this script-copying behavior into our feature_demo, so it's now being tested over and over again.

**Pull request merged**
