### PR TITLE
Remove app config from docs

### PR DESCRIPTION
**Pull request by ben-bay**

### CODE REVIEW

**Comment by lucpeterson** [comment]
a better change would be to make the examples more generic. in particular i think the redis config is useful

**Comment by koning** [comment]
The redis app.yaml is effectively in the docs already.
https://merlin.readthedocs.io/en/latest/merlin_config.html#broker-redis
https://merlin.readthedocs.io/en/latest/merlin_config.html#results-backend-redis

**Comment by lucpeterson** [comment]
ah; it looks like the amp_amqp.yaml is quoted directly in the docs. i suggest we keep it but change the paths

**Comment by ben-bay** [comment]
> ah; it looks like the amp_amqp.yaml is quoted directly in the docs. i suggest we keep it but change the paths

@lucpeterson  thanks for the catch, do you like my recent change to address this?

**Pull request merged**
