### PR TITLE
Enable walltime in spec

### PR DESCRIPTION
**Pull request by koning**
also add signal for slurm.

### CODE REVIEW

**Comment by ben-bay** [comment]
Wow! We'd better document this in the [FAQ](https://merlin.readthedocs.io/en/latest/faq.html) and maybe [workflow specification](https://merlin.readthedocs.io/en/latest/merlin_specification.html)

**Comment by ben-bay** [comment]
Looks like all tests are passing except for that ever-picky style test.

**Comment by koning** [comment]
When I run fix-style it changes too many files, is there a configuration fix for this?

**Comment by koning** [comment]
I have the merlin workflow spec section in another branch, will update this one with that file.

**Comment by ben-bay** [comment]
> When I run fix-style it changes too many files, is there a configuration fix for this?

I hope there is. Right now it's
```
isort -rc ...
black --target-version py36 ...
```

Looking thru the black flags, nothing else really pops out as a solution. What version of black and what machine are you running on? I'm using v19.10b0

**Comment by koning** [comment]
Those commands change 16 files in my branch.

sort -rc merlin
Skipped 11 files
isort -rc tests
Skipped 3 files
isort *.py
black --target-version py36 merlin
reformatted /usr/WS2/koning/mlsi/mymerlin/merlin/merlin/study/script_adapter.py
All done! ✨ 🍰 ✨
1 file reformatted, 52 files left unchanged.
black --target-version py36 tests
All done! ✨ 🍰 ✨
10 files left unchanged.
black --target-version py36 *.py
All done! ✨ 🍰 ✨
2 files left unchanged.

merlin3_7) [rztopaz188]:git stbu
## feature/koning/par_com_equals...origin/feature/koning/par_com_equals
 M merlin/celery.py
 M merlin/common/sample_index_factory.py
 M merlin/common/tasks.py
 M merlin/display.py
 M merlin/examples/workflows/feature_demo/scripts/learn.py
 M merlin/examples/workflows/flux/scripts/flux_info.py
 M merlin/main.py
 M merlin/merlin_templates.py
 M merlin/spec/expansion.py
 M merlin/study/celeryadapter.py
 M merlin/study/script_adapter.py
 M merlin/study/study.py
 M merlin/utils.py
 M setup.py
 M tests/common/test_sample_index.py
 M tests/integration/run_tests.py

merlin3_7) [rztopaz188]:black --version
black, version 19.10b0

**Comment by ben-bay** [comment]
Yeah it is frustrating. Is this on your local machine or some other node?

**Comment by koning** [comment]
This is on LC toss3 with python3.7.

**Comment by ben-bay** [comment]
I just verified that the difference is indeed between my local machine and LC toss3. Black is supposed to be deterministic, so the only thing I can think of is possibly `--system-site-packages` are different in these 2 envs?

**Comment by ben-bay** [comment]
A temporary policy could be only run `make fix-style` while on LC toss3 ?

**Comment by koning** [comment]
OK, should I ran that for this PR or in the future?

**Comment by ben-bay** [comment]
This PR now is good as-is. I'll stick to this rule in the future.

**Pull request merged**
